controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login_check:
    path: /api/login_check

login_check_options:
   path: /api/login_check
   methods: [OPTIONS]

