parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Command\DownloadFrameDataFromFatJsonCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'
    App\Command\ImportFrameDataFromFatJsonCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'
