parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
        autowire: true
        autoconfigure: true

    App\Command\DownloadFrameDataFromFatJsonCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'
    App\Command\ImportFrameDataFromFatJsonCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'
    App\Serializer\Normalizer\:
        resource: '../src/Serializer/Normalizer'
        tags:
            - { name: serializer.normalizer, priority: 100 }
        autoconfigure: true
        autowire: true


