import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import {AuthProvider} from "@/services/AuthContext";
import "./globals.css";
import Sidebar from "@/src/components/layouts/Sidebar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <AuthProvider>
            <div style={{ display: "flex" }}>
                <Sidebar />
                <main style={{ marginLeft: 280, width: "100%" }}>
                    {children}
                </main>
            </div>
        </AuthProvider>
        </body>
        </html>
    );
}
