import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import {CssBaseline, ThemeProvider} from "@mui/material";
import {AuthProvider} from "@/services/AuthContext";
import {getDesignTokens} from "@/styles/theme";
import Sidebar from "@/src/components/layouts/Sidebar";
import "./globals.css";
import {ThemeModeProvider, useMode} from "@/src/context/ThemeContext";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

// Split ThemeWrapper so we can use the useMode hook
function ThemeWrapper({children}: { children: React.ReactNode }) {
    const {mode, theme} = useMode(); // returns current mode and memoized theme
    return (
        <ThemeProvider theme={theme}>
            <CssBaseline/>
            <div style={{
                display: "flex",
                backgroundColor: theme.palette.background.default,
                color: theme.palette.text.primary
            }}>
                <Sidebar collapsed={false} toggleCollapse={function (): void {
                    throw new Error("Function not implemented.");
                }}/>
                <main style={{marginLeft: 280, width: "100%"}}>
                    {children}
                </main>
            </div>
        </ThemeProvider>
    );
}

export default function RootLayout({children}: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
            <ThemeModeProvider>
                <ThemeWrapper>{children}</ThemeWrapper>
            </ThemeModeProvider>
        </AuthProvider>
        </body>
        </html>
    );
}
