import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import {AuthProvider} from "@/services/AuthContext";
import {ThemeModeProvider} from "@/src/context/ThemeContext";
import ThemeWrapper from "@/src/context/ThemeWrapper";
import {AppRouterCacheProvider} from "@mui/material-nextjs/v15-appRouter";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AppRouterCacheProvider>
            <AuthProvider>
                <ThemeModeProvider>
                    <ThemeWrapper>{children}</ThemeWrapper>
                </ThemeModeProvider>
            </AuthProvider>
        </AppRouterCacheProvider>
        </body>
        </html>
    );
}