<?php declare(strict_types=1);

namespace App\Entity;

use App\Repository\NeutralObservationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

/**
 * One neutral move start from a replay, performed by the actor against the opponent. Rows are generated by the
 * neutral-stats import and replaced whenever their replay is imported again; they are never edited by hand.
 * Frame-state columns hold the exact extractor values at the action start (drive 0-60000, super 0-30000).
 */
#[ORM\Entity(repositoryClass: NeutralObservationRepository::class)]
#[ORM\Table(name: 'neutral_observation', schema: 'sf6')]
#[ORM\UniqueConstraint(name: 'uniq_neutral_observation_replay_source', columns: ['replay_id', 'source_observation_id'])]
#[ORM\Index(name: 'idx_neutral_observation_character_move', columns: ['character_id', 'move_id'])]
#[ORM\Index(name: 'idx_neutral_observation_character_opponent', columns: ['character_id', 'opponent_character_id'])]
#[ORM\Index(name: 'idx_neutral_observation_actor', columns: ['actor_player_id'])]
#[ORM\Index(name: 'idx_neutral_observation_opponent_player', columns: ['opponent_player_id'])]
#[ORM\Index(name: 'idx_neutral_observation_move', columns: ['move_id'])]
class NeutralObservation
{
    public const ROUTE_RAW = 'raw';
    public const ROUTE_DRIVE_RUSH = 'drive_rush';
    public const ROUTES = [self::ROUTE_RAW, self::ROUTE_DRIVE_RUSH];

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(name: 'replay_id', referencedColumnName: 'id', nullable: false, onDelete: 'CASCADE')]
    private Replay $replay;

    #[ORM\Column(name: 'source_observation_id', type: Types::STRING, length: 96)]
    private string $sourceObservationId;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(name: 'actor_player_id', referencedColumnName: 'id', nullable: false, onDelete: 'CASCADE')]
    private ReplayPlayer $actorPlayer;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(name: 'opponent_player_id', referencedColumnName: 'id', nullable: false, onDelete: 'CASCADE')]
    private ReplayPlayer $opponentPlayer;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(name: 'character_id', referencedColumnName: 'id', nullable: false, onDelete: 'CASCADE')]
    private Character $character;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(name: 'opponent_character_id', referencedColumnName: 'id', nullable: true, onDelete: 'SET NULL')]
    private ?Character $opponentCharacter = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(name: 'move_id', referencedColumnName: 'id', nullable: false, onDelete: 'CASCADE')]
    private Move $move;

    /** Extractor action id, kept for the future action id -> move mapping. */
    #[ORM\Column(name: 'action_id', type: Types::INTEGER, nullable: true)]
    private ?int $actionId = null;

    #[ORM\Column(type: Types::STRING, length: 16)]
    private string $route = self::ROUTE_RAW;

    #[ORM\Column(type: Types::FLOAT)]
    private float $spacing = 0.0;

    #[ORM\Column(name: 'catalogue_category', type: Types::STRING, length: 64, nullable: true)]
    private ?string $catalogueCategory = null;

    #[ORM\Column(name: 'entered_from', type: Types::STRING, length: 32, nullable: true)]
    private ?string $enteredFrom = null;

    #[ORM\Column(name: 'round_number', type: Types::SMALLINT, nullable: true)]
    private ?int $roundNumber = null;

    #[ORM\Column(name: 'round_timer', type: Types::SMALLINT, nullable: true)]
    private ?int $roundTimer = null;

    #[ORM\Column(name: 'replay_frame', type: Types::INTEGER, nullable: true)]
    private ?int $replayFrame = null;

    #[ORM\Column(name: 'source_index', type: Types::INTEGER, nullable: true)]
    private ?int $sourceIndex = null;

    #[ORM\Column(name: 'actor_health', type: Types::INTEGER, nullable: true)]
    private ?int $actorHealth = null;

    #[ORM\Column(name: 'actor_drive', type: Types::INTEGER, nullable: true)]
    private ?int $actorDrive = null;

    #[ORM\Column(name: 'actor_super', type: Types::INTEGER, nullable: true)]
    private ?int $actorSuper = null;

    #[ORM\Column(name: 'actor_install_active', type: Types::BOOLEAN, nullable: true)]
    private ?bool $actorInstallActive = null;

    #[ORM\Column(name: 'actor_install_remaining', type: Types::INTEGER, nullable: true)]
    private ?int $actorInstallRemaining = null;

    #[ORM\Column(name: 'opponent_health', type: Types::INTEGER, nullable: true)]
    private ?int $opponentHealth = null;

    #[ORM\Column(name: 'opponent_drive', type: Types::INTEGER, nullable: true)]
    private ?int $opponentDrive = null;

    #[ORM\Column(name: 'opponent_super', type: Types::INTEGER, nullable: true)]
    private ?int $opponentSuper = null;

    #[ORM\Column(name: 'opponent_install_active', type: Types::BOOLEAN, nullable: true)]
    private ?bool $opponentInstallActive = null;

    #[ORM\Column(name: 'opponent_install_remaining', type: Types::INTEGER, nullable: true)]
    private ?int $opponentInstallRemaining = null;

    public function getId(): ?int { return $this->id; }
    public function getReplay(): Replay { return $this->replay; }
    public function getSourceObservationId(): string { return $this->sourceObservationId; }
    public function getActorPlayer(): ReplayPlayer { return $this->actorPlayer; }
    public function getOpponentPlayer(): ReplayPlayer { return $this->opponentPlayer; }
    public function getCharacter(): Character { return $this->character; }
    public function getOpponentCharacter(): ?Character { return $this->opponentCharacter; }
    public function getMove(): Move { return $this->move; }
    public function getActionId(): ?int { return $this->actionId; }
    public function getRoute(): string { return $this->route; }
    public function getSpacing(): float { return $this->spacing; }
    public function getCatalogueCategory(): ?string { return $this->catalogueCategory; }
    public function getEnteredFrom(): ?string { return $this->enteredFrom; }
    public function getRoundNumber(): ?int { return $this->roundNumber; }
    public function getRoundTimer(): ?int { return $this->roundTimer; }
    public function getReplayFrame(): ?int { return $this->replayFrame; }
    public function getSourceIndex(): ?int { return $this->sourceIndex; }
    public function getActorHealth(): ?int { return $this->actorHealth; }
    public function getActorDrive(): ?int { return $this->actorDrive; }
    public function getActorSuper(): ?int { return $this->actorSuper; }
    public function isActorInstallActive(): ?bool { return $this->actorInstallActive; }
    public function getActorInstallRemaining(): ?int { return $this->actorInstallRemaining; }
    public function getOpponentHealth(): ?int { return $this->opponentHealth; }
    public function getOpponentDrive(): ?int { return $this->opponentDrive; }
    public function getOpponentSuper(): ?int { return $this->opponentSuper; }
    public function isOpponentInstallActive(): ?bool { return $this->opponentInstallActive; }
    public function getOpponentInstallRemaining(): ?int { return $this->opponentInstallRemaining; }
}
